apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts
  labels:
    app: posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: tanvvv/posts
        

---
apiVersion: v1
kind: Service
metadata:
  name: posts-serv
spec:
  selector:
    app: posts
  ports:
  - protocol: TCP
    port: 4001 #service
    targetPort: 4001 #pod
